CLIMATE_ETS_PROFILE = {
    "main_group": 5,
    "main_group_name": "Климат контроль",
    "group_name": "Группа 1",
    "items_per_middle_group": 12,
    "reserved_rows": [
        {"address": "5/1/0", "name": "ВСЕ Tермостаты", "dpt": "DPST-1-1"},
        {"address": "5/1/1", "name": "ВСЕ Управление Heat", "dpt": "DPST-1-1"},
        {"address": "5/1/2", "name": "ВСЕ Запись уставки", "dpt": "DPST-9-1"},
        {"address": "5/1/3", "name": "Резерв", "dpt": ""},
        {"address": "5/1/4", "name": "Резерв", "dpt": ""},
        {"address": "5/1/5", "name": "Резерв", "dpt": ""},
        {"address": "5/1/6", "name": "Резерв", "dpt": ""},
        {"address": "5/1/7", "name": "Резерв", "dpt": ""},
        {"address": "5/1/8", "name": "Резерв", "dpt": ""},
        {"address": "5/1/9", "name": "Резерв", "dpt": ""},
    ],
    "functions": [
        {"offset": 0, "label": "Текущая температура", "dpt": "DPST-9-1"},
        {"offset": 1, "label": "Статус уставки", "dpt": "DPST-9-1"},
        {"offset": 2, "label": "Запись уставки", "dpt": "DPST-9-1"},
        {"offset": 3, "label": "Вкл/выкл T", "dpt": "DPST-1-1"},
        {"offset": 4, "label": "Статус Т вкл/выкл", "dpt": "DPST-1-1"},
        {"offset": 5, "label": "Cool/Heat", "dpt": "DPST-1-100"},
        {"offset": 6, "label": "Статус Cool(0)/Heat(1)", "dpt": "DPST-1-100"},
        {"offset": 7, "label": "Управление Cool", "dpt": "DPST-1-1"},
        {"offset": 8, "label": "Статус управления Cool", "dpt": "DPST-1-1"},
        {"offset": 9, "label": "Управление Heat", "dpt": "DPST-1-1"},
        {"offset": 10, "label": "Статус управления Heat", "dpt": "DPST-1-1"},
        {"offset": 11, "label": "Скорость вентилятора", "dpt": "DPST-5-1"},
        {"offset": 12, "label": "Статус_Скорость вентилятора", "dpt": "DPST-5-1"},
        {"offset": 13, "label": "Режим вентилятора Авто", "dpt": "DPST-1-1"},
        {"offset": 14, "label": "Статус_Режим вентилятора Авто", "dpt": "DPST-1-1"},
        {"offset": 15, "label": "Температура_Вход1", "dpt": "DPST-9-1"},
        {"offset": 16, "label": "Температура_Вход2", "dpt": "DPST-9-1"},
        {"offset": 17, "label": "Доп.Heat", "dpt": "DPST-1-1"},
        {"offset": 18, "label": "Спецрежим", "dpt": "DPST-20-102"},
        {"offset": 19, "label": "Ламели", "dpt": "DPT-5"},
    ],
}
