FLOOR_HEATING_ETS_PROFILE = {
    "main_group": 3,
    "main_group_name": "Теплый пол",
    "group_name": "1-24",
    "reserved_rows": [
        {"address": "3/1/0", "name": "ВСЕ Комфорт", "dpt": "DPST-1-1"},
        {"address": "3/1/1", "name": "ВСЕ Эконом", "dpt": "DPST-1-1"},
        {"address": "3/1/2", "name": "ВСЕ Выключить", "dpt": "DPST-1-1"},
        {"address": "3/1/3", "name": "Резерв", "dpt": ""},
        {"address": "3/1/4", "name": "Резерв", "dpt": ""},
        {"address": "3/1/5", "name": "Резерв", "dpt": ""},
        {"address": "3/1/6", "name": "Резерв", "dpt": ""},
        {"address": "3/1/7", "name": "Резерв", "dpt": ""},
        {"address": "3/1/8", "name": "Резерв", "dpt": ""},
        {"address": "3/1/9", "name": "Резерв", "dpt": ""},
    ],
    "functions": [
        {"offset": 0, "label": "Вкл_Теплый_пол", "dpt": "DPST-1-1"},
        {"offset": 1, "label": "Статус_Вкл", "dpt": "DPST-1-1"},
        {"offset": 2, "label": "Заданная_температура", "dpt": "DPST-9-1"},
        {"offset": 3, "label": "Фактическая_температура", "dpt": "DPST-9-1"},
        {"offset": 4, "label": "Текущая_уставка", "dpt": "DPST-9-1"},
        {"offset": 5, "label": "Нагрев_Статус", "dpt": "DPST-1-1"},
        {"offset": 6, "label": "Клапан_%", "dpt": "DPST-5-1"},
        {"offset": 7, "label": "Клапан_%_Статус", "dpt": "DPST-5-1"},
        {"offset": 8, "label": "Авария", "dpt": "DPST-1-1"},
        {"offset": 9, "label": "Резерв", "dpt": ""},
    ],
}
