FLOOR_HEATING_ETS_PROFILE = {
    "main_group": 3,
    "main_group_name": "Теплый пол",
    "group_name": "1-12",
    "items_per_middle_group": 12,
    "reserved_rows": [
        {"address": "3/1/0", "name": "ВСЕ Tермостаты ТП", "dpt": "DPST-1-1"},
        {"address": "3/1/1", "name": "ВСЕ Управление_Heat ТП", "dpt": "DPST-1-1"},
        {"address": "3/1/2", "name": "ВСЕ Запись уставки ТП", "dpt": "DPST-9-1"},
        {"address": "3/1/3", "name": "Резерв", "dpt": ""},
        {"address": "3/1/4", "name": "Резерв", "dpt": ""},
        {"address": "3/1/5", "name": "Резерв", "dpt": ""},
        {"address": "3/1/6", "name": "Резерв", "dpt": ""},
        {"address": "3/1/7", "name": "Резерв", "dpt": ""},
        {"address": "3/1/8", "name": "Резерв", "dpt": ""},
        {"address": "3/1/9", "name": "Резерв", "dpt": ""},
    ],
    "functions": [
        {"offset": 0, "label": "Текущая температура", "dpt": "DPST-9-1", "reserved": False},
        {"offset": 1, "label": "Статус уставки", "dpt": "DPST-9-1", "reserved": False},
        {"offset": 2, "label": "Запись уставки", "dpt": "DPST-9-1", "reserved": False},
        {"offset": 3, "label": "Вкл/выкл T", "dpt": "DPST-1-1", "reserved": False},
        {"offset": 4, "label": "Статус Т вкл/выкл", "dpt": "DPST-1-1", "reserved": False},
        {"offset": 5, "label": "Управление Heat", "dpt": "DPST-1-1", "reserved": False},
        {"offset": 6, "label": "Статус управления Heat", "dpt": "DPST-1-1", "reserved": False},
        {"offset": 7, "label": "Ошибка датчика", "dpt": "DPST-1-1", "reserved": False},
        {"offset": 8, "label": "Перегрев", "dpt": "DPST-1-1", "reserved": False},
        {"offset": 9, "label": "Резерв", "dpt": "DPST-1-1", "reserved": True},
    ],
}
