MECHANISMS_ETS_PROFILE = {
    "main_group": 2,
    "main_group_name": "Механизмы",
    "group_name": "1-24",
    "reserved_rows": [
        {"address": "2/1/0", "name": "ВСЕ Движение", "dpt": "DPST-1-1"},
        {"address": "2/1/1", "name": "ВСЕ Стоп", "dpt": "DPST-1-1"},
        {"address": "2/1/2", "name": "ВСЕ Реверс", "dpt": "DPST-1-1"},
        {"address": "2/1/3", "name": "Резерв", "dpt": ""},
        {"address": "2/1/4", "name": "Резерв", "dpt": ""},
        {"address": "2/1/5", "name": "Резерв", "dpt": ""},
        {"address": "2/1/6", "name": "Резерв", "dpt": ""},
        {"address": "2/1/7", "name": "Резерв", "dpt": ""},
        {"address": "2/1/8", "name": "Резерв", "dpt": ""},
        {"address": "2/1/9", "name": "Резерв", "dpt": ""},
    ],
    "functions": [
        {"offset": 0, "label": "Движение_Шторы", "dpt": "DPST-1-1"},
        {"offset": 1, "label": "Стоп_Шторы", "dpt": "DPST-1-1"},
        {"offset": 2, "label": "Положение_%_Шторы", "dpt": "DPST-5-1"},
        {"offset": 3, "label": "Положение_%_Статус", "dpt": "DPST-5-1"},
        {"offset": 4, "label": "Положение_Ламели", "dpt": "DPST-5-1"},
        {"offset": 5, "label": "Ламели_%_Статус", "dpt": "DPST-5-1"},
        {"offset": 6, "label": "Движение_Статус", "dpt": "DPST-1-1"},
        {"offset": 7, "label": "Статус_направления[0/1]", "dpt": "DPST-1-1"},
        {"offset": 8, "label": "Реверс [0/1]", "dpt": "DPST-1-1"},
        {"offset": 9, "label": "Резерв", "dpt": ""},
    ],
}
