ROOMS_ETS_PROFILE = {
    "main_group": 0,
    "main_group_name": "Центральные функции",
    "middle_group": 1,
    "middle_group_name": "Помещения",
    "start_address": 20,
    "addresses_per_room": 20,
    "functions": [
        {"offset": 0, "label": "Весь свет", "dpt": "DPST-1-1"},
        {"offset": 1, "label": "Все шторы движ", "dpt": "DPST-1-1"},
        {"offset": 2, "label": "Все шторы стоп", "dpt": "DPST-1-1"},
        {"offset": 3, "label": "Громкость+", "dpt": "DPST-1-1"},
        {"offset": 4, "label": "Громкость-", "dpt": "DPST-1-1"},
        {"offset": 5, "label": "ТВ Вкл", "dpt": "DPST-1-1"},
        {"offset": 6, "label": "ТВ OFF", "dpt": "DPST-1-1"},
        {"offset": 7, "label": "Музыка Вкл", "dpt": "DPST-1-1"},
        {"offset": 8, "label": "Музыка OFF", "dpt": "DPST-1-1"},
        {"offset": 9, "label": "RGB", "dpt": "DPST-1-1"},
        {"offset": 10, "label": "Температура", "dpt": "DPST-9-1"},
        {"offset": 11, "label": "Резерв1", "dpt": ""},
        {"offset": 12, "label": "Резерв2", "dpt": ""},
        {"offset": 13, "label": "Резерв3", "dpt": ""},
        {"offset": 14, "label": "Резерв4", "dpt": ""},
        {"offset": 15, "label": "Резерв5", "dpt": ""},
        {"offset": 16, "label": "Резерв6", "dpt": ""},
        {"offset": 17, "label": "Резерв7", "dpt": ""},
        {"offset": 18, "label": "Резерв8", "dpt": ""},
        {"offset": 19, "label": "Резерв9", "dpt": ""},
    ],
}
